### ISSUE TITLE
FYI: install_requires error. Fix is upgrade setuptools

### ISSUE THREAD

**Issue by initiate6** [Revolution1/Flask-WhooshAlchemyPlus#4]
Full error:

error in Flask-WhooshAlchemyPlus setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers

To resolve:

pip install --upgrade setuptools

Just wanted to add a issue encase anyone ran across the same thing.

**Comment by Revolution1** [comment]
thanks~
